name: tests

on:
  pull_request:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

    - name: Run pytest
      run: |
        if [ -d tests/ ]; then
          source venv/bin/activate
          code=$(
            coverage run --source=src/ -m pytest tests/ > test_report.txt
            echo $?
          )
          cat test_report.txt
          status=
          if [[ code = 0 ]]; then status=success; else status=failure; fi
          echo "status: ${status}"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -f state="$status" \
            -f context='tests' \
            -f description="Test status: $status" \
            &> /dev/null
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check coverage
      run: |
        # Fetch enough history for a common merge-base commit
        git fetch -q origin ${{ github.event.pull_request.head.ref }} --depth $(( ${{ github.event.pull_request.commits }} + 1 ))
        # Fetch is smart enough to keep commits fetched minimal if it finds local history already has a commit from the base branch:
        git fetch -q origin ${{ github.event.pull_request.base.ref }}
        source venv/bin/activate
        coverage json -q
        # git diff 02e1262ff488822d6a0a6c59f75ddd229cc2294f..HEAD > diff.txt
        git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > diff.txt
        code=$(
          python .github/workflows/diff_coverage.py diff.txt coverage.json > diff_coverage.txt
          echo $?
        )
        status=
        if [[ code = 0 ]]; then status=success; else status=failure; fi
        echo "status: ${status}"
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
          -f state="$status" \
          -f context='coverage' \
          -f description="Coverage status: $status" \
          &> /dev/null
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create coverage comment
      run: |
        if [ -f .coverage ]; then
          source venv/bin/activate
          REPORT=$'diff coverage:\n'
          REPORT+=$'```\n'
          REPORT+=$(cat diff_coverage.txt)
          REPORT+=$'\n```'
          echo "comment: ${REPORT}"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
            -f body="$REPORT" \
            &> /dev/null
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
