name: tests

on:
  pull_request:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - name: Install gh
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

    - name: Run pytest
      run: |
        source venv/bin/activate
        if [ -d tests/ ]; then
          code=$(
            coverage run --source=src/ -m pytest tests/ > test_report
            echo $?
          )
          status=
          if [[ code = 0 ]]; then status=success; else status=failure; fi
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
            -f state='$status' \
            -f context='tests'
            -f description='Tests passed, maybe'
        fi

        
    - name: Get coverage
      run: |
        if [ -f .coverage ]; then
          source venv/bin/activate
          REPORT=$'```\n'
          REPORT+=$(coverage report -m)
          REPORT+=$'\n```'
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
          -f body="$REPORT"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
